// app/frontend/lib/components/ui/avatar/avatar.svelte
<script lang="ts">
  import { cn } from '@/lib/utils'
  import { Avatar as AvatarPrimitive } from 'bits-ui'

  let {
    class: className,
    ref = $bindable(null),
    loadingStatus = $bindable('loading'),
    ...restProps
  }: AvatarPrimitive.RootProps = $props()
</script>

<AvatarPrimitive.Root
  bind:loadingStatus
  bind:ref
  class={cn(
    'relative flex size-10 shrink-0 overflow-hidden rounded-full',
    className
  )}
  {...restProps}
/>

// assets/js/components/ui/avatar.tsx
import * as AvatarPrimitive from '@radix-ui/react-avatar'

import { cn } from '@/lib/utils'
import type { ComponentProps } from 'react'

function Avatar({
  className,
  ...props
}: ComponentProps<typeof AvatarPrimitive.Root>) {
  return (
    <AvatarPrimitive.Root
      data-slot='avatar'
      className={cn(
        'relative flex size-8 shrink-0 overflow-hidden rounded-full',
        className
      )}
      {...props}
    />
  )
}

function AvatarImage({
  className,
  ...props
}: ComponentProps<typeof AvatarPrimitive.Image>) {
  return (
    <AvatarPrimitive.Image
      data-slot='avatar-image'
      className={cn('aspect-square size-full', className)}
      {...props}
    />
  )
}

function AvatarFallback({
  className,
  ...props
}: ComponentProps<typeof AvatarPrimitive.Fallback>) {
  return (
    <AvatarPrimitive.Fallback
      data-slot='avatar-fallback'
      className={cn(
        'bg-muted flex size-full items-center justify-center rounded-full',
        className
      )}
      {...props}
    />
  )
}

export { Avatar, AvatarFallback, AvatarImage }
